### ISSUE TITLE
infinite scroll isn't loading anymore? 

### ISSUE THREAD

**Issue by ajtpak** [FlandreDaisuki/EHInfiniteScroll#2]
Cleared my cookies and cache recently, now infinitescroll isn't working. When I went to exhentai, there was an icon to enable unsafe scritps on the right side (I assumed it was that since I tried reinstalling it), and it didn't do anything after I enabled it, can you help? 

EDIT: Fixed it by changed line 17 to this: 

const TAGFLAGGING = UCONFIG.match(/tf_([^\-]*)/) && UCONFIG.match(/tf_([^\-]*)/)[1] !== 'n';

**Comment by FlandreDaisuki** [comment]
I find that the cookie format has changed, but my browser works fine.
I want to fix this issue, but I can't reproduce this bug.
So, I want to know if you comment out `line 17` and change `line 56` as following
```
if (DISPLAY === 'Thumb') {
```
work in your browser?

**Comment by kusanagi1777** [comment]
After changing those two lines it works for me again in firefox
